### ISSUE TITLE
about shows update

### ISSUE THREAD

**Issue by gowtham20** [emailradhesh/topbestsite#1]
Hello radhesh, do we need to update reality shows links manually or its auto update as topbestsites website updates, if we need to add manually where should we update (at my topbestsite_com.py or here), example biggboss

**Comment by emailradhesh** [comment]
@gowtham20 in this repository there is docs folder. It is exposed as [website](https://emailradhesh.github.io/topbestsite). When you open TopBestSite in Kodi the content is brought from this site. I'll update the content of the website once a week, mostly after weekend. To update the content I use scripts/create*.sh files respectively. So the content is due for update either today or tomorrow.

**Comment by emailradhesh** [comment]
Updated videos to the latest.
