### ISSUE TITLE
Check and update BiggBoss reality show using Google Apps Script (GAS)

### ISSUE THREAD

**Issue by emailradhesh** [emailradhesh/topbestsite#2]
### What is the current workings?

1. Shell script is used to check BiggBoss.
1. It gets first 7 episode videos and writes **bigg-boss-kannada-season-4-videos.html** file.
1. The first 2 lines in the file looks like
`<p>bigg-boss-kannada-season-4-07112016-episode-30</p><iframe src="http://www.dailymotion.com/embed/video/k5L1cOJwivD7UukA1Ik?autoplay=0&amp;logo=0&amp;hideInfos=0&amp;start=0&amp;syndication=202279&amp;foreground=&amp;highlight=&amp;background=" width="600" height="360" frameborder="0"></iframe><br>`
`<p>bigg-boss-kannada-season-4-07112016-episode-30_Alternate</p><iframe src="http://hqq.tv/player/embed_player.php?vid=271272278205221253254260253229275265194271217261258&amp;autoplay=no" width="720" height="450" frameborder="0"></iframe><br>`
1. The script is to be executed in BASH environment manually.
1. Then committed and pushed.

### What is needed now?

Instead of the shell script the above steps should be done using Google Apps Script such that  it will be triggered automatically.

**Comment by emailradhesh** [comment]
Until now

1. Got authorization passed between GAS and Github by following the article [Working with Github repository files using Google Apps Script: Examples in getting, writing and committing content](https://mashe.hawksey.info/2016/08/working-with-github-repository-files-using-google-apps-script-examples-in-getting-writing-and-committing-content/).
2. Tested
  1. Create new file and committed
  2. Appended the content and committed 
2. Wrote sample script to fetch episodes and video frames of BiggBoss

**Comment by emailradhesh** [comment]
Got basic regex

1. For episode links
`/(https?:\/\/.*bigg-boss-kannada-season-4-[0-9].*?[^"]+)/g`
1. For DM video frames
`/<iframe(.*).*(daily).*\/iframe>/g`
1. For non DM video frames
`/<iframe(.*).*(hqq|open).*\/iframe>/g`
Need to find if non DM can be simply other than DM instead of specific words.

**Comment by gowtham20** [comment]
hello radhesh , help;- where to paste autoexec.py ? do i need to delete topbestsite.py from vstream,

**Comment by emailradhesh** [comment]
@gowtham20 sorry for delayed reply. The file autoexec.py should be in .kodi/userdata directory.

**Comment by emailradhesh** [comment]
The intention of acquiring video frames using Google Apps Scripts is done. Today triggered commit was successful.

At the same time need to check what is broken in add-on script. Any new things in vstream? Not sure.
